### ISSUE TITLE
strace fails with: invalid system call '%file'

### ISSUE THREAD

**Issue by jklmnn** [LionelDraghi/smk#1]
When running  `smk` strace fails with the following error:
```
/usr/bin/strace: invalid system call '%file'
```

Replacing `%file` with just `file works for me.
```
diff --git a/src/smk-settings.ads b/src/smk-settings.ads
index d2a3033..4743378 100644
--- a/src/smk-settings.ads
+++ b/src/smk-settings.ads
@@ -46,7 +46,7 @@ private package Smk.Settings is
    Smk_File_Prefix       : constant String := ".smk."; -- used for all Smk files
    Strace_Outfile_Suffix : constant String := "strace_output";
    Strace_Cmd            : constant String := "/usr/bin/strace";
-   Strace_Opt            : constant String := "-y -q -qq -f -e trace=%file -o ";
+   Strace_Opt            : constant String := "-y -q -qq -f -e trace=file -o ";
    -- -y  : print paths associated with file descriptor arguments (between <>)
    -- -q  : suppress messages about attaching, detaching, etc.
    -- -qq : suppress messages about process exit status.
```

**Comment by LionelDraghi** [comment]
Works on my box with or without, so let's remove it!
(I got this notation [here](https://strace.io/))
Thanks!

**Comment by LionelDraghi** [comment]
from http://www.man7.org/linux/man-pages/man1/strace.1.html 

>  -e trace=%file
>  -e trace=file (deprecated)
>                    Trace all system calls which take a file name as an
>                    argument.  You can think of this as an abbreviation for
>                    -e trace=open,stat,chmod,unlink,...  which is useful to
>                    seeing what files the process is referencing.
>                    Furthermore, using the abbreviation will ensure that you
>                    don't accidentally forget to include a call like lstat in
>                    the list.  Betchya woulda forgot that one.

So, the notation seems to be deprecated without "%".

**Comment by jklmnn** [comment]
The next stable release of Debian (Buster) also notes the notation without `%` as deprecated. So for the long term readding the `%` would be the right way.
