### ISSUE TITLE
Clean option for compilation files

### ISSUE THREAD

**Issue by mgrojo** [LionelDraghi/smk#10]
Interesting idea!

I see that the current `--clean` option is for removing the internal smk files. There should be another for deleting the generated files by the compilation: what "make clean" traditionally does, but automatically determined by smk, e.g. object files and executables.

**Comment by LionelDraghi** [comment]
Thanks for the comment, and yes, good idea : `smk` should provide both functionality.

Could be a --clean-targets options.

Or simply --delete (cf. 
https://www.gnu.org/prep/standards/standards.html#Command_002dLine-Interfaces)

**Comment by mgrojo** [comment]
The pair `--clean` `--delete` seems a bit unclear to me, because in the `make` context, clean always means removing the compiled files. Users might expect the opposite behaviour, unless they care to read (or reread the documentation).

**Comment by LionelDraghi** [comment]
I agree.
I propose:
--clean : remove targets, as in typical makefile
--reset : renames the actual --clean, that is remove smk internal files

**Comment by mgrojo** [comment]
Perfect naming. I like it.
