### ISSUE TITLE
build fails \gprbuild: object directory /home/$USER/smk/obj/ does not exist

### ISSUE THREAD

**Issue by k3ck3c** [LionelDraghi/smk#17]
Hello

Trying to build a Dockerfile, I  could not get smk to work, and the same on a Debian

Debian 9 following the installation procedure

gprbuild -P smk.gpr                                                                                                                                       
\gprbuild: object directory /home/gg/smk/obj/ does not exist

uname -arn                                                                                                                                                
Linux debian9 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux

any idea ?

**Comment by LionelDraghi** [comment]
I added a note on creating the obj dir in [index.md#Downloading and building].
