### ISSUE TITLE
It's not clear why anyone should use this

### ISSUE THREAD

**Issue by Lucretia** [LionelDraghi/smk#4]
What's the difference between putting the gcc commands into a bash script? There must be something smk is doing differently. Maybe you should document this.

**Comment by LionelDraghi** [comment]
Thanks for this : if it's not obvious from the quickstart page, the quickstart page is wrong!
The answer is that the bash script will run all command each time, while smk will run only what need to be run.

I will make it more obvious with a simple exemple in the [Usage](index.md#usage) section of the Quickstart page. 
Tell me if it's more clrear for you.
